export const liqours = [
  {
    id: 1,
    title: "Captain Morgan 750ml",
    category: "whiskey",
    img: require("../images/whiskey1.png"),
    price: 850.0,
  },
  {
    id: 2,
    title: "Hennesy 750ml",
    category: "congac",
    img: require("../images/congac.png"),
    price: 4450.0,
  },
  {
    id: 3,
    title: "Gilbeys gin 750ml",
    category: "gin",
    img: require("../images/gin.png"),
    price: 1200.0,
  },
  {
    id: 4,
    title: "Black and White 750ml",
    category: "whiskey",
    img: require("../images/whiskey2.png"),
    price: 1150.0,
  },
  {
    id: 5,
    title: "White Cap Can 500ml",
    category: "beer",
    img: require("../images/beer1.png"),
    price: 190.0,
  },
  {
    id: 6,
    title: "Hunter's Choice 750ml",
    category: "whiskey",
    img: require("../images/whiskey4.png"),
    price: 850.0,
  },
  {
    id: 7,
    title: "Guiness Can 500ml",
    category: "beer",
    img: require("../images/beer3.png"),
    price: 200.0,
  },
  {
    id: 8,
    title: "4th street",
    category: "wine",
    img: require("../images/wine.png"),
    price: 850.0,
  },
  {
    id: 9,
    title: "Jack Daniels",
    category: "whiskey",
    img: require("../images/whiskey3.png"),
    price: 4550.0,
  },
  {
    id: 10,
    title: "Viceroy 1ltr",
    category: "brandy",
    img: require("../images/brandy.png"),
    price: 5000.0,
  },
  {
    id: 11,
    title: "Smirnoff Vodka 750ml",
    category: "vodka",
    img: require("../images/vodka1.png"),
    price: 1400.0,
  },
  {
    id: 12,
    title: "Tusker Lite",
    category: "beer",
    img: require("../images/beer4.png"),
    price: 250.0,
  },
  {
    id: 13,
    title: "Pilsner",
    category: "beer",
    img: require("../images/beer7.png"),
    price: 200.0,
  },
  {
    id: 14,
    title: "Kibao Vodka 750ml",
    category: "vodka",
    img: require("../images/vodka2.png"),
    price: 850.0,
  },
];
